services:
  app:
    &app
    image: fastapi_app:latest
    build: .
    ports:
      - 8080:8080
    restart: always
    environment:
      FASTAPI_APP_POSTGRES_URL: postgresql://fastapi_app:fastapi_app@db:5432/fastapi_app
      FASTAPI_APP_NATS_URLS: nats://nats:4222/
      FASTAPI_APP_REDIS_URL: redis://valkey/
    # For live reload on fs changes
    develop:
      watch:
        - path: ./fastapi_app
          target: /app/src/fastapi_app
          action: sync+restart
    depends_on:
      db:
        condition: service_healthy
      nats:
        condition: service_healthy
      valkey:
        condition: service_healthy

  taskiq-worker:
    <<: *app
    ports: []
    command: [ taskiq, worker, -fsd, fastapi_app.tkq:broker, -w, "1", --max-fails, "1"]

  taskiq-scheduler:
    <<: *app
    ports: []
    command: [ taskiq, scheduler, -fsd, fastapi_app.tkq_sched:scheduler ]

  db:
    image: "postgres:15.2-bullseye"
    hostname: db
    environment:
      POSTGRES_DB: "fastapi_app"
      POSTGRES_USER: "fastapi_app"
      POSTGRES_PASSWORD: "fastapi_app"
    restart: always
    healthcheck:
      test: pg_isready -U fastapi_app
      interval: 2s
      timeout: 3s
      retries: 40

  nats:
    image: nats:2.10-alpine
    hostname: nats
    command:
      - "-js"
      - "-m"
      - "8222"
    healthcheck:
      test:
        - "CMD"
        - "sh"
        - "-c"
        - "wget http://localhost:8222/healthz -q -O - | xargs | grep ok || exit 1"
      interval: 5s
      timeout: 3s
      retries: 5

  valkey:
    image: bitnami/valkey:8.0.2
    hostname: valkey
    restart: always
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    healthcheck:
      test: valkey-cli ping
      interval: 1s
      timeout: 3s
      retries: 50
